const TABLE_HEADER = [
    {
        title: "No. Nota"
    },
    {
        title: "Nama"
    },
    {
        title: "Status"
    }
];

const TABLE_CONTENT = [
    {
        id: 1,
        receiptNumber: '001',
        customerName: "Gita",
        isPaidOff: true,
        status: "Masuk",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 2,
        receiptNumber: '002',
        customerName: "Go Youn Jung",
        isPaidOff: false,
        status: "Masuk",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 3,
        receiptNumber: '003',
        customerName: "Jung So Min",
        isPaidOff: true,
        status: "Disetrika",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 4,
        receiptNumber: '004',
        customerName: "Muthe",
        isPaidOff: true,
        status: "Dicuci",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 5,
        receiptNumber: '005',
        customerName: "Helisma",
        isPaidOff: true,
        status: "Sudah Diambil",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 6,
        receiptNumber: '006',
        customerName: "Gracia",
        isPaidOff: false,
        status: "Masuk",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 7,
        receiptNumber: '007',
        customerName: "Indira",
        isPaidOff: false,
        status: "Dicuci",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 8,
        receiptNumber: '008',
        customerName: "Yessica",
        isPaidOff: true,
        status: "Sudah Diambil",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 9,
        receiptNumber: '009',
        customerName: "Mo Deok",
        isPaidOff: true,
        status: "Masuk",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 10,
        receiptNumber: '010',
        customerName: "Naksu",
        isPaidOff: true,
        status: "Dicuci",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 11,
        receiptNumber: '011',
        customerName: "Robin",
        isPaidOff: true,
        status: "Disetrika",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 12,
        receiptNumber: '012',
        customerName: "Frankie",
        isPaidOff: true,
        status: "Dicuci",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 13,
        receiptNumber: '013',
        customerName: "Sekar",
        isPaidOff: true,
        status: "Dicuci",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
    {
        id: 14,
        receiptNumber: '014',
        customerName: "Andarini",
        isPaidOff: true,
        status: "Masuk",
        createdAt: new Date(),
        branch: 'Blimbing',
        customerAddress: 'Jakarta',
        customerContact: '081322119212',
        service: 'Satuan',
        totalPrice: 20_000,
        estimateDay: 3,
    },
];


export { TABLE_HEADER, TABLE_CONTENT };